language: go

go:
  - 1.7.x

services:
  - mysql

before_install:
  - mysql -u $DB_USERNAME -h $DB_HOSTNAME --password=$DB_PASSWORD $DB_DATABASE < ./auto/db_clean.sql

install:
  - go get -u github.com/Masterminds/glide
  - glide install

script: 
  - touch .env
  - openssl genrsa -out private.pem 2048
  - openssl rsa -in private.pem -outform PEM -pubout -out public.pem
  - export JWT_PUBLIC_KEY=$(pwd)/public.pem
  - export JWT_PRIVATE_KEY=$(pwd)/private.pem
  - go test -p=1 -v $(go list ./... | grep -vi 'vendor\|testutils\|routetesting')

after_script:
  - mysql -u $DB_USERNAME -h $DB_HOSTNAME --password=$DB_PASSWORD $DB_DATABASE < ./auto/db_clean.sql
